// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwaggerTraining.DataAccess;

namespace SwaggerTraining.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SwaggerTraining.Models.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            DateOfBirth = new DateTime(1610, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eddard",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            DateOfBirth = new DateTime(1652, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jaime",
                            LastName = "Lannister"
                        },
                        new
                        {
                            Id = new Guid("d902b665-1190-4c70-9915-b9c2d7680450"),
                            DateOfBirth = new DateTime(1653, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Daenerys",
                            LastName = "Targaryen"
                        });
                });

            modelBuilder.Entity("SwaggerTraining.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            Description = "A training for OpenAPI and Swashbuckle.",
                            DeveloperId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "OpenAPI Training"
                        },
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "A training for RESTful APIs in .NETCore.",
                            DeveloperId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "RESTful APIs Training"
                        },
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9ba2"),
                            Description = "A training for Docker.",
                            DeveloperId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Docker Training"
                        },
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c7a"),
                            Description = "A training for Git.",
                            DeveloperId = new Guid("d902b665-1190-4c70-9915-b9c2d7680450"),
                            Name = "Git Training"
                        });
                });

            modelBuilder.Entity("SwaggerTraining.Models.Project", b =>
                {
                    b.HasOne("SwaggerTraining.Models.Developer", "Developer")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("SwaggerTraining.Models.Developer", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
